### ISSUE TITLE
Unable to get cloud shell environment 

### ISSUE THREAD

**Issue by abhishekubangera** [googleapis/python-shell#122]
I'm trying to connect connect to google cloud shell/terminal from my local (mac) and execute/trigger a shell script (also few other commands) present in the ephemeral VM (cloud shell).
Using the below code to get the environment details but hitting error

code:
    from google.cloud import shell_v1
    from google.oauth2 import service_account
    credentials = service_account.Credentials.from_service_account_file('/path_to_service_account_key.json')
    client = shell_v1.CloudShellServiceClient(credentials=credentials)
    #  or client = shell_v1.CloudShellServiceClient().from_service_account_json('/path_to_service_account_key.json')
    # Initialize request argument(s)
    request = shell_v1.GetEnvironmentRequest(name="users/me/environments/default",)
    # Make the request
    operation = client.get_environment(request=request)
    print("Waiting for operation to complete...")
    response = operation.result()
    # Handle the response
    print(response)

Error:
Traceback (most recent call last):
  File "/Users/aubanger/Desktop/sandboxpy3/py3_env4/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 50, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/aubanger/Desktop/sandboxpy3/py3_env4/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/aubanger/Desktop/sandboxpy3/py3_env4/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Internal error encountered."
	debug_error_string = "{"created":"@1658842961.439535000","description":"Error received from peer ipv6:[2404:6800:4007:825::200a]:443","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Internal error encountered.","grpc_status":13}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aubanger/Desktop/sandboxpy3/gcp_sandbox/gcp_test5.py", line 14, in <module>
    operation = client.get_environment(request=request)
  File "/Users/aubanger/Desktop/sandboxpy3/py3_env4/lib/python3.8/site-packages/google/cloud/shell_v1/services/cloud_shell_service/client.py", line 529, in get_environment
    response = rpc(
  File "/Users/aubanger/Desktop/sandboxpy3/py3_env4/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/aubanger/Desktop/sandboxpy3/py3_env4/lib/python3.8/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/Users/aubanger/Desktop/sandboxpy3/py3_env4/lib/python3.8/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/Users/aubanger/Desktop/sandboxpy3/py3_env4/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 52, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.

Please let me know if I'm following a right approach here, if not please suggest, thanks

**Comment by engelke** [comment]
Thanks for the report.

I just went through the same code as above, with no errors. One note: since the client is not the Async version, the `call client.get_environment(request=request)` returns the result, not an operation. However, the returned result is correct.

This may have been due to a problem since fixed, but it works properly now. If the problem recurs, reopen this comment with more details.
